### ISSUE TITLE
Download packs failing

### ISSUE THREAD

**Issue by fadangalini** [thebezelproject/BezelProject#73] opened 2021-06-03 22:49 UTC
Sorry if this is covered but can't find it if it has.

Using a pi4 fully updated, just installed the bezel project, which looks like it installed fine.
when i try to download a pack, started with mega drive, it starts, then around 40 something % it fails, it's too fast to read what the error is. Did the same for NES which i tried next. Tried for segacd as i guessed it would be a smaller pack and it finished and works fine. Brilliant by the way!!

Any ideas why the others are failing downloading? Recap, they start downloading then fail but I can't see what the error is... Many thanks for any help

**Comment by thebezelproject** [comment] 2021-06-03 23:09
Nothing specific comes to mind, however we have had a number of reports of various issues with a pi4. So far, all issues have been addressed by doing a full update of the OS and RetroPie. If you haven't tried that, please check and report back.

**Comment by fadangalini** [comment] 2021-06-04 16:33
Thanks for your reply. As far as I know it's all up to date. RetroPie image downloaded from the official website a couple of weeks ago. I took a photo of the error when trying to download the mega drive pack as it flashed on screen so fast.

Just before it failed
![Screenshot_20210604-163502_Video Player](https://user-images.githubusercontent.com/69798443/120834180-973cba00-c55a-11eb-9c75-b6615a0258ad.jpg)

The error that flashed up before going back to the menu.
![Screenshot_20210604-163452_Video Player](https://user-images.githubusercontent.com/69798443/120834162-90ae4280-c55a-11eb-8c23-55f0b1b6f9d1.jpg)

**Comment by thebezelproject** [comment] 2021-06-04 21:58
Please force the updates as I listed to make sure of a baseline. Since all functions of the script work here and other places, the problem is on your end somewhere. Before doing any updates, please check your free space on the image to make sure it isn't full, or nearly full.

**Comment by fadangalini** [comment] 2021-06-04 22:23
No problem, will do. Can you please tell me how to do those updates you want? I have space on the sd card.

**Comment by thebezelproject** [comment] 2021-06-04 23:10
https://retropie.org.uk/docs/Updating-RetroPie/

**Comment by fadangalini** [comment] 2021-06-05 08:46
OK. thank you. I'm just going away for the weekend so won't be able to progress. As soon as i'm back I will do this and get back to you. Thanks.

**Comment by fadangalini** [comment] 2021-06-06 19:38
I made a full backup just in case. Did a full update, script, packages, kernel. All done then tried to download the mega drive pack again, had the same error unfortunately. Now the LightGuns have stopped working, so not sure what the updates changed. Glad I made the backup.

**Comment by thebezelproject** [comment] 2021-06-06 21:28
Backups are key!

Out of ideas for the moment.

**Comment by fadangalini** [comment] 2021-06-07 12:33
Damn. Well I've restored and found the gun usb had become loose. So the update wasn't the problem. haha. All updated again but still fails to download a pack. Tried turning off the firewall as per something I found online but didn't help.

**Comment by thebezelproject** [comment] 2021-06-07 14:36
There are a number of ideas on this page: https://stackoverflow.com/questions/38378914/how-to-fix-git-error-rpc-failed-curl-56-gnutls

Have you tried any of these possible fixes?

**Comment by fadangalini** [comment] 2021-06-07 22:44
Thanks. Haven't tried any of those but will give them a go tomorrow and let you know how it goes.

**Comment by fadangalini** [comment] 2021-06-09 13:54
Fixed!! I tired everything from the link but nothing worked. Tried via my mobile network and it worked fine. Bit more googling and it was virgin media web safe causing the problem. I added "GitHub.com" to the allowed list in the web safe settings, and no downloading without issue.

Thanks for your help

**Comment by thebezelproject** [comment] 2021-06-09 17:08
Wow, who would have thought? Many thanks for updating the thread here. Hopefully it can help others in the future.

**Closed by thebezelproject** 2021-06-09 17:08 UTC
